const fs = require('fs');
const icons = require('../node_modules/@heroicons/vue/outline/index');

let content = `// This file is automatically generated. Run \`npm run scripts\` or any other command to re-generate it!

import { defineAsyncComponent, defineComponent, h } from 'vue';

const IconLoader = defineComponent({
    props: {
        size: {
            type: Number,
            default: 5,
        }
    },
    render() {
        return h('div', { class: \`overflow-hidden h-${this.size} w-${this.size}\` });
    }
});

export default {
`;

Object.keys(icons).forEach(icon => {
    let name = icon.replace('Icon', '');
    content += `    ${name}: defineAsyncComponent({ loader: () => import(/* webpackChunkName: "${icon}" */'@heroicons/vue/outline/esm/${icon}'), loadingComponent: IconLoader }),\n`;
});

// Static Voyager icons
content += `    Bread: defineAsyncComponent(() => import(/* webpackChunkName: "BreadIcon" */'./icons/bread')),\n`;
content += `    Helm: defineAsyncComponent(() => import(/* webpackChunkName: "HelmIcon" */'./icons/helm')),\n`;

content += "}";

fs.writeFile('resources/assets/js/icons.js', content, (err) => {
    if (err) throw err;
    console.log('Icons file generated at "resources/assets/js/icons.js"');
});