const fs = require('fs');
const icons = require('../node_modules/@heroicons/vue/outline/index');

let content = `// This file is automatically generated. Run \`npm run scripts\` or any other command to re-generate it!

import { defineAsyncComponent, defineComponent, h } from 'vue';
import LoadingIcon from '@heroicons/vue/outline/esm/RefreshIcon';
import ErrorIcon from '@heroicons/vue/outline/esm/XCircleIcon';

const IconLoader = defineComponent({
    props: {
        size: {
            type: Number,
            default: 5,
        }
    },
    render() {
        return h('div', { class: \`overflow-hidden h-\${this.size} w-\${this.size} animate-spin-reverse\` }, [ h(LoadingIcon) ]);
    }
});

const IconError = defineComponent({
    props: {
        size: {
            type: Number,
            default: 5,
        },
        icon: {
            type: String
        }
    },
    mounted() {
        console.warn(\`Icon "\${this.icon}" could not be loaded. Please reload the page to give it another try!\`);
    },
    render() {
        return h('div', { class: \`overflow-hidden h-\${this.size} w-\${this.size}\`, style: "color: red !important" }, [ h(ErrorIcon) ]);
    }
});

export default {
`;

Object.keys(icons).forEach(icon => {
    let name = icon.replace('Icon', '');
    content += `    ${name}: defineAsyncComponent({ loader: () => import(/* webpackChunkName: "${icon}" */'@heroicons/vue/outline/esm/${icon}'), loadingComponent: IconLoader, errorComponent: IconError }),\n`;
});

// Static Voyager icons
content += `    Bread: defineAsyncComponent({ loader: () => import(/* webpackChunkName: "BreadIcon" */'./icons/bread'), loadingComponent: IconLoader, errorComponent: IconError}),\n`;
content += `    Helm: defineAsyncComponent({ loader: () => import(/* webpackChunkName: "HelmIcon" */'./icons/helm'), loadingComponent: IconLoader, errorComponent: IconError}),\n`;

content += "}";

fs.writeFile('resources/assets/js/icons.js', content, (err) => {
    if (err) throw err;
    console.log('Icons file generated at "resources/assets/js/icons.js"');
});